// Auto-generated by `cargo run -p generator -- docs`
// Do not edit manually.

#import "@preview/cmarker:0.1.8": render as md
#import "manual_util.typ": *

== General

=== Code11 <sym-code11>

#md("Code 11", h1-level: 4)

Shortcut: `#code11(data)` \
Symbology value: `"Code11"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`check_digits`], typst-type("int"), [#md("Number of modulo-11 check digits to add to the symbol.", h1-level: 5)], [`2`],
)

=== C25Standard <sym-c25-standard>

#md("2 of 5 Standard (Matrix)", h1-level: 4)

Shortcut: `#c25-standard(data)` \
Symbology value: `"C25Standard"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`check_digit`], typst-type("bool"), [#md("Whether to add a check digit to 2 of 5 code.", h1-level: 5)], [--],
  [`hide_check_digit`], typst-type("bool"), [#md("Whether to hide the check digit from Human Readable Text (HRT).", h1-level: 5)], [--],
)

=== C25Inter <sym-c25-inter>

#md("2 of 5 Interleaved", h1-level: 4)

Shortcut: `#c25-inter(data)` \
Symbology value: `"C25Inter"`

_Uses shared options from `C25Options`._

=== C25IATA <sym-c25-iata>

#md("2 of 5 IATA", h1-level: 4)

Shortcut: `#c25-iata(data)` \
Symbology value: `"C25IATA"`

_Uses shared options from `C25Options`._

=== C25Logic <sym-c25-logic>

#md("2 of 5 Data Logic", h1-level: 4)

Shortcut: `#c25-logic(data)` \
Symbology value: `"C25Logic"`

_Uses shared options from `C25Options`._

=== C25Ind <sym-c25-ind>

#md("2 of 5 Industrial", h1-level: 4)

Shortcut: `#c25-ind(data)` \
Symbology value: `"C25Ind"`

_Uses shared options from `C25Options`._

=== Code39 <sym-code39>

#md("Code 39", h1-level: 4)

Shortcut: `#code39(data)` \
Symbology value: `"Code39"`

=== ExCode39 <sym-ex-code39>

#md("Extended Code 39", h1-level: 4)

Shortcut: `#ex-code39(data)` \
Symbology value: `"ExCode39"`

=== Codabar <sym-codabar>

#md("Codabar", h1-level: 4)

Shortcut: `#codabar(data)` \
Symbology value: `"Codabar"`

=== Code128 <sym-code128>

#md("Code 128", h1-level: 4)

Shortcut: `#code128(data)` \
Symbology value: `"Code128"`

=== Code16k <sym-code16k>

#md("Code 16k", h1-level: 4)

Shortcut: `#code16k(data)` \
Symbology value: `"Code16k"`

=== Code49 <sym-code49>

#md("Code 49", h1-level: 4)

Shortcut: `#code49(data)` \
Symbology value: `"Code49"`

=== Code93 <sym-code93>

#md("Code 93", h1-level: 4)

Shortcut: `#code93(data)` \
Symbology value: `"Code93"`

=== Flat <sym-flat>

#md("Flattermarken", h1-level: 4)

Shortcut: `#flat(data)` \
Symbology value: `"Flat"`

=== Telepen <sym-telepen>

#md("Telepen Alpha", h1-level: 4)

Shortcut: `#telepen(data)` \
Symbology value: `"Telepen"`

=== MSIPlessey <sym-msi-plessey>

#md("MSI Plessey is based on `Plessey` and
developed by MSE Data Corporation.

MSI Plessey has a range of check digit options that are selectable
by setting `check_digits`.

Numeric (digits 0-9) input can be encoded, up to a maximum of 65
digits.", h1-level: 4)

Shortcut: `#msi-plessey(data)` \
Symbology value: `"MSIPlessey"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`check_digits`], [`MSIPlesseyCheckDigits`], [#md("Specifies mode for generated check digits.", h1-level: 5)], [--],
  [`hide_check_digit`], typst-type("bool"), [#md("Whether to hide the check digit from Human Readable Text (HRT).", h1-level: 5)], [--],
)

=== FIM <sym-fim>

#md("Facing Identification Mark", h1-level: 4)

Shortcut: `#fim(data)` \
Symbology value: `"FIM"`

=== LOGMARS <sym-logmars>

Also accepted as: `"Logmars"`

#md("LOGMARS", h1-level: 4)

Shortcut: `#logmars(data)` \
Symbology value: `"LOGMARS"`

=== Code128AB <sym-code128ab>

Also accepted as: `"CODE128B"`

#md("Code 128 (Suppress Code Set C)", h1-level: 4)

Shortcut: `#code128ab(data)` \
Symbology value: `"Code128AB"`

=== VIN <sym-vin>

#md("Vehicle Identification Number", h1-level: 4)

Shortcut: `#vin(data)` \
Symbology value: `"VIN"`

=== Plessey <sym-plessey>

#md("Plessey (Code) symbology was developed by the Plessey Company Ltd.
in the UK.

The symbol can encode data consisting of digits (0-9) or letters A-F
up to a maximum of 65 characters and includes a CRC check digit.", h1-level: 4)

Shortcut: `#plessey(data)` \
Symbology value: `"Plessey"`

=== TelepenNum <sym-telepen-num>

#md("Telepen Numeric", h1-level: 4)

Shortcut: `#telepen-num(data)` \
Symbology value: `"TelepenNum"`

=== Code32 <sym-code32>

#md("Code 32", h1-level: 4)

Shortcut: `#code32(data)` \
Symbology value: `"Code32"`

=== Channel <sym-channel>

#md("Channel Code", h1-level: 4)

Shortcut: `#channel(data)` \
Symbology value: `"Channel"`

=== BC412 <sym-bc412>

#md("IBM BC412 (SEMI T1-95)", h1-level: 4)

Shortcut: `#bc412(data)` \
Symbology value: `"BC412"`

=== DXFilmEdge <sym-dx-film-edge>

#md("DX Film Edge Barcode on 35mm and APS films", h1-level: 4)

Shortcut: `#dx-film-edge(data)` \
Symbology value: `"DXFilmEdge"`

== Retail & Product Identification

=== EANX <sym-eanx>

#md("Variable length EAN variant", h1-level: 4)

Shortcut: `#eanx(data)` \
Symbology value: `"EANX"`

_Uses shared options from `UPCEOptions`._

=== EANXChk <sym-eanx-chk>

#md("Variable length EAN variant with digit check", h1-level: 4)

Shortcut: `#eanx-chk(data)` \
Symbology value: `"EANXChk"`

_Uses shared options from `UPCEOptions`._

=== EANXCC <sym-eanx-cc>

#md("Variable length composite EAN variant", h1-level: 4)

Shortcut: `#eanx-cc(data)` \
Symbology value: `"EANXCC"`

_Uses shared options from `UPCEOptions`._

=== EAN2 <sym-ean-2>

Also accepted as: `"EAN2Addon"`

#md("EAN/UPC 2-digit

This symbology is almost never used as standalone and is generally
appended to other one-dimensional barcodes.", h1-level: 4)

Shortcut: `#ean-2(data)` \
Symbology value: `"EAN2"`

_Uses shared options from `UPCEOptions`._

=== EAN5 <sym-ean-5>

Also accepted as: `"EAN5Addon"`

#md("EAN/UPC 5-digit

This symbology is almost never used as standalone and is generally
appended to other one-dimensional barcodes.", h1-level: 4)

Shortcut: `#ean-5(data)` \
Symbology value: `"EAN5"`

_Uses shared options from `UPCEOptions`._

=== EAN8 <sym-ean-8>

Also accepted as: `"GTIN8"`

#md("EAN-8 (European Article Number) GTIN-8

In addition EAN-2 and EAN-5 add-on symbols can be added by using the
'+' character as a separator after EAN-8 data.", h1-level: 4)

Shortcut: `#ean-8(data)` \
Symbology value: `"EAN8"`

_Uses shared options from `UPCEOptions`._

=== EAN13 <sym-ean-13>

Also accepted as: `"GTIN13"`

#md("EAN-13 (European Article Number) is a standard 13-digit barcode used
in retail across Europe.

EAN-13 requires 12-digit numerical input. The check digit is
calculated by Zint.

In addition EAN-2 and EAN-5 add-on symbols can be added by using the
'+' character as a separator after EAN-13 data.", h1-level: 4)

Shortcut: `#ean-13(data)` \
Symbology value: `"EAN13"`

_Uses shared options from `UPCEOptions`._

=== EAN14 <sym-ean-14>

Also accepted as: `"GTIN14"`

#md("EAN-14

EAN-14 requires 13-digit numerical input. The check digit is
calculated by Zint.

In addition EAN-2 and EAN-5 add-on symbols can be added by using the
'+' character as a separator after EAN-14 data.", h1-level: 4)

Shortcut: `#ean-14(data)` \
Symbology value: `"EAN14"`

_Uses shared options from `UPCEOptions`._

=== EAN8CC <sym-ean-8-cc>

#md("EAN-8 Composite", h1-level: 4)

Shortcut: `#ean-8-cc(data)` \
Symbology value: `"EAN8CC"`

_Uses shared options from `UPCEOptions`._

=== EAN13CC <sym-ean-13-cc>

#md("EAN-13 Composite", h1-level: 4)

Shortcut: `#ean-13-cc(data)` \
Symbology value: `"EAN13CC"`

_Uses shared options from `UPCEOptions`._

=== UPCA <sym-upca>

#md("UPC-A is used in the United States for retail applications. The
symbol requires an 11-digit article number. The check digit is
calculated by Zint.

In addition EAN-2 and EAN-5 add-on symbols can be added by using the
'+' character as a separator before EAN-2/EAN-5 data.

If input data already includes the check digit,
`UPCAChk` can be used.", h1-level: 4)

Shortcut: `#upca(data)` \
Symbology value: `"UPCA"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`addon_gap`], typst-type("int"), [#md("Gap between the main symbol and an add-on in multiples of the X-dimension.", h1-level: 5)], [`9`],
  [`guard_descent`], typst-type("float"), [#md("Height in X-dimensions that the guard bars descend below the main bars.", h1-level: 5)], [`5.0`],
)

=== UPCAChk <sym-upca-chk>

#md("UPC-A variant that expects check digit to be included in input data.

See `UPCA` for details.", h1-level: 4)

Shortcut: `#upca-chk(data)` \
Symbology value: `"UPCAChk"`

_Uses shared options from `UPCAOptions`._

=== UPCE <sym-upce>

#md("UPC-E", h1-level: 4)

Shortcut: `#upce(data)` \
Symbology value: `"UPCE"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`addon_gap`], typst-type("int"), [#md("Gap between the main symbol and an add-on in multiples of the X-dimension.", h1-level: 5)], [`7`],
  [`guard_descent`], typst-type("float"), [#md("Height in X-dimensions that the guard bars descend below the main bars.", h1-level: 5)], [`5.0`],
)

=== UPCEChk <sym-upce-chk>

#md("UPC-E including check digit", h1-level: 4)

Shortcut: `#upce-chk(data)` \
Symbology value: `"UPCEChk"`

_Uses shared options from `UPCEOptions`._

=== ISBNX <sym-isbnx>

#md("ISBN

Relevant check digit needs to be present in the input data and will
be verified before the symbol is generated.

In addition EAN-2 and EAN-5 add-on symbols can be added using the +
character as with UPC symbols.", h1-level: 4)

Shortcut: `#isbnx(data)` \
Symbology value: `"ISBNX"`

_Uses shared options from `UPCEOptions`._

=== NVE18 <sym-nve18>

#md("NVE-18 (SSCC-18)", h1-level: 4)

Shortcut: `#nve18(data)` \
Symbology value: `"NVE18"`

=== ITF14 <sym-itf14>

#md("ITF-14, also known as UPC Shipping Container Symbol or Case Code, is
based on Interleaved Code 2 of 5 and requires a 13-digit numeric
input (digits 0-9).", h1-level: 4)

Shortcut: `#itf14(data)` \
Symbology value: `"ITF14"`

=== UPCACC <sym-upca-cc>

#md("UPC-A Composite", h1-level: 4)

Shortcut: `#upca-cc(data)` \
Symbology value: `"UPCACC"`

=== UPCECC <sym-upce-cc>

#md("UPC-E Composite", h1-level: 4)

Shortcut: `#upce-cc(data)` \
Symbology value: `"UPCECC"`

== GS1 DataBar

=== GS1128 <sym-gs1-128>

Also accepted as: `"EAN128"`

#md("GS1-128", h1-level: 4)

Shortcut: `#gs1-128(data)` \
Symbology value: `"GS1128"`

=== DBarOmn <sym-dbar-omn>

Also accepted as: `"RSS14"`

#md("GS1 DataBar Omnidirectional", h1-level: 4)

Shortcut: `#dbar-omn(data)` \
Symbology value: `"DBarOmn"`

=== DBarLtd <sym-dbar-ltd>

#md("GS1 DataBar Limited", h1-level: 4)

Shortcut: `#dbar-ltd(data)` \
Symbology value: `"DBarLtd"`

=== DBarExp <sym-dbar-exp>

#md("GS1 DataBar Expanded", h1-level: 4)

Shortcut: `#dbar-exp(data)` \
Symbology value: `"DBarExp"`

=== DBarStk <sym-dbar-stk>

Also accepted as: `"RSS14Stk"`

#md("GS1 DataBar Stacked", h1-level: 4)

Shortcut: `#dbar-stk(data)` \
Symbology value: `"DBarStk"`

=== DBarOmnStk <sym-dbar-omn-stk>

Also accepted as: `"RSS14StackOmni"`

#md("GS1 DataBar Stacked Omnidirectional", h1-level: 4)

Shortcut: `#dbar-omn-stk(data)` \
Symbology value: `"DBarOmnStk"`

=== DBarExpStk <sym-dbar-exp-stk>

#md("GS1 DataBar Expanded Stacked", h1-level: 4)

Shortcut: `#dbar-exp-stk(data)` \
Symbology value: `"DBarExpStk"`

=== GS1128CC <sym-gs1-128-cc>

Also accepted as: `"EAN128CC"`

#md("GS1-128 Composite", h1-level: 4)

Shortcut: `#gs1-128-cc(data)` \
Symbology value: `"GS1128CC"`

=== DBarOmnCC <sym-dbar-omn-cc>

Also accepted as: `"RSS14CC"`

#md("GS1 DataBar Omnidirectional Composite", h1-level: 4)

Shortcut: `#dbar-omn-cc(data)` \
Symbology value: `"DBarOmnCC"`

=== DBarLtdCC <sym-dbar-ltd-cc>

Also accepted as: `"RSSLtdCC"`

#md("GS1 DataBar Limited Composite", h1-level: 4)

Shortcut: `#dbar-ltd-cc(data)` \
Symbology value: `"DBarLtdCC"`

=== DBarExpCC <sym-dbar-exp-cc>

Also accepted as: `"RSSExpCC"`

#md("GS1 DataBar Expanded Composite", h1-level: 4)

Shortcut: `#dbar-exp-cc(data)` \
Symbology value: `"DBarExpCC"`

=== DBarStkCC <sym-dbar-stk-cc>

Also accepted as: `"RSS14StackCC"`

#md("GS1 DataBar Stacked Composite", h1-level: 4)

Shortcut: `#dbar-stk-cc(data)` \
Symbology value: `"DBarStkCC"`

=== DBarOmnStkCC <sym-dbar-omn-stk-cc>

Also accepted as: `"RSS14OmniCC"`

#md("GS1 DataBar Stacked Omnidirectional Composite", h1-level: 4)

Shortcut: `#dbar-omn-stk-cc(data)` \
Symbology value: `"DBarOmnStkCC"`

=== DBarExpStkCC <sym-dbar-exp-stk-cc>

Also accepted as: `"RSSExpStackCC"`

#md("GS1 DataBar Expanded Stacked Composite", h1-level: 4)

Shortcut: `#dbar-exp-stk-cc(data)` \
Symbology value: `"DBarExpStkCC"`

== 2D Matrix Codes

=== PDF417 <sym-pdf417>

#md("PDF417", h1-level: 4)

Shortcut: `#pdf417(data)` \
Symbology value: `"PDF417"`

=== PDF417Comp <sym-pdf417-comp>

Also accepted as: `"PDF417Trunc"`

#md("Compact PDF417 (Truncated PDF417)", h1-level: 4)

Shortcut: `#pdf417-comp(data)` \
Symbology value: `"PDF417Comp"`

=== MaxiCode <sym-maxicode>

#md("MaxiCode symbology is designed for the identification of parcels.

MaxiCode symbols can be encoded in one of five modes which are
specified using the `mode` option.

This symbology uses Latin-1 character encoding by default but also
supports the ECI encoding mechanism. The maximum length of text
which can be placed in a MaxiCode symbol depends on the type of
characters used in the text and `mode`, see
`MaxiCodeMode` variants for details.", h1-level: 4)

Shortcut: `#maxicode(data)` \
Symbology value: `"MaxiCode"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`mode`], [`MaxiCodeMode < 'o >`], [#md("MaxiCode mode and corresponding options to use for encoding.

See `MaxiCodeMode` for details.", h1-level: 5)], [--],
  [`scm_prefix`], typst-type("int"), [#md("2-digit version used in **ISO/IEC 15434 Format 01
(transportation)** prefix `[)>\R01\Gvv` which will be
prepended to ASCII-compatible secondary message data.

This prefix will only be used with
`StructuredCarrierMessage`
and will be ignored otherwise.

Only values in range [0, 99] are valid, and zint will return
an error if provided data ECI isn't ASCII-compatible.

This is only a utility option and prefix can be included in
secondary message data manually.", h1-level: 5)], [--],
)

=== QRCode <sym-qrcode>

#md("QR Code", h1-level: 4)

Shortcut: `#qrcode(data)` \
Symbology value: `"QRCode"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`error_correction`], [`QRErrorCorrection`], [--], [--],
  [`size`], [`QRSize`], [--], [--],
  [`full_multibyte`], typst-type("bool"), [--], [--],
  [`mask`], [`QRMask`], [--], [--],
)

=== DataMatrix <sym-data-matrix>

#md("Data Matrix (ECC200)", h1-level: 4)

Shortcut: `#data-matrix(data)` \
Symbology value: `"DataMatrix"`

=== CodablockF <sym-codablock-f>

#md("Codablock-F", h1-level: 4)

Shortcut: `#codablock-f(data)` \
Symbology value: `"CodablockF"`

=== MicroPDF417 <sym-micro-pdf417>

#md("MicroPDF417", h1-level: 4)

Shortcut: `#micro-pdf417(data)` \
Symbology value: `"MicroPDF417"`

=== Aztec <sym-aztec>

#md("Aztec Code", h1-level: 4)

Shortcut: `#aztec(data)` \
Symbology value: `"Aztec"`

=== MicroQR <sym-micro-qr>

#md("Micro QR Code", h1-level: 4)

Shortcut: `#micro-qr(data)` \
Symbology value: `"MicroQR"`

=== DotCode <sym-dotcode>

#md("DotCode", h1-level: 4)

Shortcut: `#dotcode(data)` \
Symbology value: `"DotCode"`

=== HanXin <sym-hanxin>

#md("Han Xin (Chinese Sensible) Code", h1-level: 4)

Shortcut: `#hanxin(data)` \
Symbology value: `"HanXin"`

=== AzRune <sym-azrune>

#md("Aztec Runes", h1-level: 4)

Shortcut: `#azrune(data)` \
Symbology value: `"AzRune"`

=== CodeOne <sym-code-one>

#md("Code One", h1-level: 4)

Shortcut: `#code-one(data)` \
Symbology value: `"CodeOne"`

=== GridMatrix <sym-grid-matrix>

#md("Grid Matrix", h1-level: 4)

Shortcut: `#grid-matrix(data)` \
Symbology value: `"GridMatrix"`

=== Ultra <sym-ultra>

#md("Ultracode symbology uses a grid of coloured elements to encode data.

ECI and GS1 modes are supported.", h1-level: 4)

Shortcut: `#ultra(data)` \
Symbology value: `"Ultra"`

*Options:*

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, center + horizon, left + horizon, center + horizon),
  stroke: gray.lighten(60%),
  fill: (_, row) => if row == 0 { blue.lighten(80%) },
  [*Option*], [*Type*], [*Description*], [*Default*],
  [`error_correction`], [`UltracodeErrorCorrection`], [#md("Specifies amount of symbol holding error correction data.", h1-level: 5)], [--],
  [`compression`], typst-type("bool"), [#md("Enables support for data compression.

## Experimental

Ultracode data compression is experimental and should not be
used in a production environment.", h1-level: 5)], [--],
  [`revision`], [`UltracodeRevision`], [#md("Specifies which Ultracode revision to use for symbol
encoding.", h1-level: 5)], [--],
)

=== RMQR <sym-rmqr>

#md("Rectangular Micro QR Code (rMQR)", h1-level: 4)

Shortcut: `#rmqr(data)` \
Symbology value: `"RMQR"`

== Postal Services

=== DPLEIT <sym-dpleit>

#md("Deutsche Post Leitcode is based on Interleaved Code 2 of 5 and is
used by Deutsche Post for mailing purposes. Leitcode requires a
13-digit numerical input and includes a check digit.", h1-level: 4)

Shortcut: `#dpleit(data)` \
Symbology value: `"DPLEIT"`

=== DPIDENT <sym-dpident>

#md("Deutsche Post Identcode is based on Interleaved Code 2 of 5 and is
used by Deutsche Post for mailing purposes. Identcode requires
11-digit numerical input and includes a check digit.", h1-level: 4)

Shortcut: `#dpident(data)` \
Symbology value: `"DPIDENT"`

=== Postnet <sym-postnet>

#md("USPS (U.S. Postal Service) POSTNET", h1-level: 4)

Shortcut: `#postnet(data)` \
Symbology value: `"Postnet"`

=== CEPNet <sym-cepnet>

#md("Brazilian CEPNet Postal Code", h1-level: 4)

Shortcut: `#cepnet(data)` \
Symbology value: `"CEPNet"`

=== AusPost <sym-aus-post>

#md("Australia Post Standard Customer", h1-level: 4)

Shortcut: `#aus-post(data)` \
Symbology value: `"AusPost"`

=== AusReply <sym-aus-reply>

#md("Australia Post Reply Paid", h1-level: 4)

Shortcut: `#aus-reply(data)` \
Symbology value: `"AusReply"`

=== AusRoute <sym-aus-route>

#md("Australia Post Routing", h1-level: 4)

Shortcut: `#aus-route(data)` \
Symbology value: `"AusRoute"`

=== AusRedirect <sym-aus-redirect>

#md("Australia Post Redirection", h1-level: 4)

Shortcut: `#aus-redirect(data)` \
Symbology value: `"AusRedirect"`

=== RM4SCC <sym-rm4scc>

#md("Royal Mail 4-State Customer Code", h1-level: 4)

Shortcut: `#rm4scc(data)` \
Symbology value: `"RM4SCC"`

=== JapanPost <sym-japan-post>

#md("Japanese Postal Code", h1-level: 4)

Shortcut: `#japan-post(data)` \
Symbology value: `"JapanPost"`

=== KoreaPost <sym-korea-post>

#md("Korea Post", h1-level: 4)

Shortcut: `#korea-post(data)` \
Symbology value: `"KoreaPost"`

=== Planet <sym-planet>

#md("USPS PLANET", h1-level: 4)

Shortcut: `#planet(data)` \
Symbology value: `"Planet"`

=== USPSIMail <sym-usps-imail>

Also accepted as: `"OneCode"`

#md("USPS Intelligent Mail (OneCode)", h1-level: 4)

Shortcut: `#usps-imail(data)` \
Symbology value: `"USPSIMail"`

=== KIX <sym-kix>

#md("Dutch Post KIX Code", h1-level: 4)

Shortcut: `#kix(data)` \
Symbology value: `"KIX"`

=== DAFT <sym-daft>

#md("DAFT Code", h1-level: 4)

Shortcut: `#daft(data)` \
Symbology value: `"DAFT"`

=== DPD <sym-dpd>

#md("DPD Code", h1-level: 4)

Shortcut: `#dpd(data)` \
Symbology value: `"DPD"`

=== Mailmark2D <sym-mailmark-2d>

#md("Royal Mail 2D Mailmark (CMDM) (Data Matrix)", h1-level: 4)

Shortcut: `#mailmark-2d(data)` \
Symbology value: `"Mailmark2D"`

=== UPUS10 <sym-upus10>

#md("Universal Postal Union S10", h1-level: 4)

Shortcut: `#upus10(data)` \
Symbology value: `"UPUS10"`

=== Mailmark4S <sym-mailmark-4s>

Also accepted as: `"Mailmark"`

#md("Royal Mail 4-State Mailmark", h1-level: 4)

Shortcut: `#mailmark-4s(data)` \
Symbology value: `"Mailmark4S"`

=== UPNQR <sym-upnqr>

#md("UPNQR (Univerzalnega Plačilnega Naloga QR)", h1-level: 4)

Shortcut: `#upnqr(data)` \
Symbology value: `"UPNQR"`

== Healthcare & Pharmaceutical

=== Pharma <sym-pharma>

#md("Pharmacode One-Track", h1-level: 4)

Shortcut: `#pharma(data)` \
Symbology value: `"Pharma"`

=== PZN <sym-pzn>

#md("Pharmazentralnummer", h1-level: 4)

Shortcut: `#pzn(data)` \
Symbology value: `"PZN"`

=== PharmaTwo <sym-pharma-two>

#md("Pharmacode Two-Track", h1-level: 4)

Shortcut: `#pharma-two(data)` \
Symbology value: `"PharmaTwo"`

=== HIBC128 <sym-hibc-128>

#md("HIBC (Health Industry Barcode) Code 128", h1-level: 4)

Shortcut: `#hibc-128(data)` \
Symbology value: `"HIBC128"`

=== HIBC39 <sym-hibc-39>

#md("HIBC Code 39", h1-level: 4)

Shortcut: `#hibc-39(data)` \
Symbology value: `"HIBC39"`

=== HIBCDM <sym-hibc-dm>

#md("HIBC Data Matrix", h1-level: 4)

Shortcut: `#hibc-dm(data)` \
Symbology value: `"HIBCDM"`

=== HIBCQR <sym-hibc-qr>

#md("HIBC QR Code", h1-level: 4)

Shortcut: `#hibc-qr(data)` \
Symbology value: `"HIBCQR"`

=== HIBCPDF <sym-hibc-pdf>

#md("HIBC PDF417", h1-level: 4)

Shortcut: `#hibc-pdf(data)` \
Symbology value: `"HIBCPDF"`

=== HIBCMicroPDF <sym-hibc-micro-pdf>

Also accepted as: `"HIBCMicPDF"`

#md("HIBC MicroPDF417", h1-level: 4)

Shortcut: `#hibc-micro-pdf(data)` \
Symbology value: `"HIBCMicroPDF"`

=== HIBCCodablockF <sym-hibc-codablock-f>

Also accepted as: `"HIBCBlockF"`

#md("HIBC Codablock-F", h1-level: 4)

Shortcut: `#hibc-codablock-f(data)` \
Symbology value: `"HIBCCodablockF"`

=== HIBCAztec <sym-hibc-aztec>

#md("HIBC Aztec Code", h1-level: 4)

Shortcut: `#hibc-aztec(data)` \
Symbology value: `"HIBCAztec"`

