// Auto-generated by `cargo run -p generator -- wrappers`
// Do not edit manually.

#import "core.typ": barcode

#let code11(data, options: (:), ..args) = barcode(
  data,
  "Code11",
  options: options,
  ..args,
)
#let c25-standard(data, options: (:), ..args) = barcode(
  data,
  "C25Standard",
  options: options,
  ..args,
)
#let c25-inter(data, options: (:), ..args) = barcode(
  data,
  "C25Inter",
  options: options,
  ..args,
)
#let c25-iata(data, options: (:), ..args) = barcode(
  data,
  "C25IATA",
  options: options,
  ..args,
)
#let c25-logic(data, options: (:), ..args) = barcode(
  data,
  "C25Logic",
  options: options,
  ..args,
)
#let c25-ind(data, options: (:), ..args) = barcode(
  data,
  "C25Ind",
  options: options,
  ..args,
)
#let code39(data, options: (:), ..args) = barcode(
  data,
  "Code39",
  options: options,
  ..args,
)
#let ex-code39(data, options: (:), ..args) = barcode(
  data,
  "ExCode39",
  options: options,
  ..args,
)
#let eanx(data, options: (:), ..args) = barcode(
  data,
  "EANX",
  options: options,
  ..args,
)
#let eanx-chk(data, options: (:), ..args) = barcode(
  data,
  "EANXChk",
  options: options,
  ..args,
)
#let eanx-cc(data, options: (:), ..args) = barcode(
  data,
  "EANXCC",
  options: options,
  ..args,
)
#let ean-2(data, options: (:), ..args) = barcode(
  data,
  "EAN2",
  options: options,
  ..args,
)
#let ean-5(data, options: (:), ..args) = barcode(
  data,
  "EAN5",
  options: options,
  ..args,
)
#let ean-8(data, options: (:), ..args) = barcode(
  data,
  "EAN8",
  options: options,
  ..args,
)
#let ean-13(data, options: (:), ..args) = barcode(
  data,
  "EAN13",
  options: options,
  ..args,
)
#let ean-14(data, options: (:), ..args) = barcode(
  data,
  "EAN14",
  options: options,
  ..args,
)
#let ean-8-cc(data, options: (:), ..args) = barcode(
  data,
  "EAN8CC",
  options: options,
  ..args,
)
#let ean-13-cc(data, options: (:), ..args) = barcode(
  data,
  "EAN13CC",
  options: options,
  ..args,
)
#let gs1-128(data, options: (:), ..args) = barcode(
  data,
  "GS1128",
  options: options,
  ..args,
)
#let codabar(data, options: (:), ..args) = barcode(
  data,
  "Codabar",
  options: options,
  ..args,
)
#let code128(data, options: (:), ..args) = barcode(
  data,
  "Code128",
  options: options,
  ..args,
)
#let dpleit(data, options: (:), ..args) = barcode(
  data,
  "DPLEIT",
  options: options,
  ..args,
)
#let dpident(data, options: (:), ..args) = barcode(
  data,
  "DPIDENT",
  options: options,
  ..args,
)
#let code16k(data, options: (:), ..args) = barcode(
  data,
  "Code16k",
  options: options,
  ..args,
)
#let code49(data, options: (:), ..args) = barcode(
  data,
  "Code49",
  options: options,
  ..args,
)
#let code93(data, options: (:), ..args) = barcode(
  data,
  "Code93",
  options: options,
  ..args,
)
#let flat(data, options: (:), ..args) = barcode(
  data,
  "Flat",
  options: options,
  ..args,
)
#let dbar-omn(data, options: (:), ..args) = barcode(
  data,
  "DBarOmn",
  options: options,
  ..args,
)
#let dbar-ltd(data, options: (:), ..args) = barcode(
  data,
  "DBarLtd",
  options: options,
  ..args,
)
#let dbar-exp(data, options: (:), ..args) = barcode(
  data,
  "DBarExp",
  options: options,
  ..args,
)
#let telepen(data, options: (:), ..args) = barcode(
  data,
  "Telepen",
  options: options,
  ..args,
)
#let upca(data, options: (:), ..args) = barcode(
  data,
  "UPCA",
  options: options,
  ..args,
)
#let upca-chk(data, options: (:), ..args) = barcode(
  data,
  "UPCAChk",
  options: options,
  ..args,
)
#let upce(data, options: (:), ..args) = barcode(
  data,
  "UPCE",
  options: options,
  ..args,
)
#let upce-chk(data, options: (:), ..args) = barcode(
  data,
  "UPCEChk",
  options: options,
  ..args,
)
#let postnet(data, options: (:), ..args) = barcode(
  data,
  "Postnet",
  options: options,
  ..args,
)
#let msi-plessey(data, options: (:), ..args) = barcode(
  data,
  "MSIPlessey",
  options: options,
  ..args,
)
#let fim(data, options: (:), ..args) = barcode(
  data,
  "FIM",
  options: options,
  ..args,
)
#let logmars(data, options: (:), ..args) = barcode(
  data,
  "LOGMARS",
  options: options,
  ..args,
)
#let pharma(data, options: (:), ..args) = barcode(
  data,
  "Pharma",
  options: options,
  ..args,
)
#let pzn(data, options: (:), ..args) = barcode(
  data,
  "PZN",
  options: options,
  ..args,
)
#let pharma-two(data, options: (:), ..args) = barcode(
  data,
  "PharmaTwo",
  options: options,
  ..args,
)
#let cepnet(data, options: (:), ..args) = barcode(
  data,
  "CEPNet",
  options: options,
  ..args,
)
#let pdf417(data, options: (:), ..args) = barcode(
  data,
  "PDF417",
  options: options,
  ..args,
)
#let pdf417-comp(data, options: (:), ..args) = barcode(
  data,
  "PDF417Comp",
  options: options,
  ..args,
)
#let maxicode(data, options: (:), ..args) = barcode(
  data,
  "MaxiCode",
  options: options,
  ..args,
)
#let qrcode(data, options: (:), ..args) = barcode(
  data,
  "QRCode",
  options: options,
  ..args,
)
#let code128ab(data, options: (:), ..args) = barcode(
  data,
  "Code128AB",
  options: options,
  ..args,
)
#let aus-post(data, options: (:), ..args) = barcode(
  data,
  "AusPost",
  options: options,
  ..args,
)
#let aus-reply(data, options: (:), ..args) = barcode(
  data,
  "AusReply",
  options: options,
  ..args,
)
#let aus-route(data, options: (:), ..args) = barcode(
  data,
  "AusRoute",
  options: options,
  ..args,
)
#let aus-redirect(data, options: (:), ..args) = barcode(
  data,
  "AusRedirect",
  options: options,
  ..args,
)
#let isbnx(data, options: (:), ..args) = barcode(
  data,
  "ISBNX",
  options: options,
  ..args,
)
#let rm4scc(data, options: (:), ..args) = barcode(
  data,
  "RM4SCC",
  options: options,
  ..args,
)
#let data-matrix(data, options: (:), ..args) = barcode(
  data,
  "DataMatrix",
  options: options,
  ..args,
)
#let vin(data, options: (:), ..args) = barcode(
  data,
  "VIN",
  options: options,
  ..args,
)
#let codablock-f(data, options: (:), ..args) = barcode(
  data,
  "CodablockF",
  options: options,
  ..args,
)
#let nve18(data, options: (:), ..args) = barcode(
  data,
  "NVE18",
  options: options,
  ..args,
)
#let japan-post(data, options: (:), ..args) = barcode(
  data,
  "JapanPost",
  options: options,
  ..args,
)
#let korea-post(data, options: (:), ..args) = barcode(
  data,
  "KoreaPost",
  options: options,
  ..args,
)
#let dbar-stk(data, options: (:), ..args) = barcode(
  data,
  "DBarStk",
  options: options,
  ..args,
)
#let dbar-omn-stk(data, options: (:), ..args) = barcode(
  data,
  "DBarOmnStk",
  options: options,
  ..args,
)
#let dbar-exp-stk(data, options: (:), ..args) = barcode(
  data,
  "DBarExpStk",
  options: options,
  ..args,
)
#let planet(data, options: (:), ..args) = barcode(
  data,
  "Planet",
  options: options,
  ..args,
)
#let micro-pdf417(data, options: (:), ..args) = barcode(
  data,
  "MicroPDF417",
  options: options,
  ..args,
)
#let usps-imail(data, options: (:), ..args) = barcode(
  data,
  "USPSIMail",
  options: options,
  ..args,
)
#let plessey(data, options: (:), ..args) = barcode(
  data,
  "Plessey",
  options: options,
  ..args,
)
#let telepen-num(data, options: (:), ..args) = barcode(
  data,
  "TelepenNum",
  options: options,
  ..args,
)
#let itf14(data, options: (:), ..args) = barcode(
  data,
  "ITF14",
  options: options,
  ..args,
)
#let kix(data, options: (:), ..args) = barcode(
  data,
  "KIX",
  options: options,
  ..args,
)
#let aztec(data, options: (:), ..args) = barcode(
  data,
  "Aztec",
  options: options,
  ..args,
)
#let daft(data, options: (:), ..args) = barcode(
  data,
  "DAFT",
  options: options,
  ..args,
)
#let dpd(data, options: (:), ..args) = barcode(
  data,
  "DPD",
  options: options,
  ..args,
)
#let micro-qr(data, options: (:), ..args) = barcode(
  data,
  "MicroQR",
  options: options,
  ..args,
)
#let hibc-128(data, options: (:), ..args) = barcode(
  data,
  "HIBC128",
  options: options,
  ..args,
)
#let hibc-39(data, options: (:), ..args) = barcode(
  data,
  "HIBC39",
  options: options,
  ..args,
)
#let hibc-dm(data, options: (:), ..args) = barcode(
  data,
  "HIBCDM",
  options: options,
  ..args,
)
#let hibc-qr(data, options: (:), ..args) = barcode(
  data,
  "HIBCQR",
  options: options,
  ..args,
)
#let hibc-pdf(data, options: (:), ..args) = barcode(
  data,
  "HIBCPDF",
  options: options,
  ..args,
)
#let hibc-micro-pdf(data, options: (:), ..args) = barcode(
  data,
  "HIBCMicroPDF",
  options: options,
  ..args,
)
#let hibc-codablock-f(data, options: (:), ..args) = barcode(
  data,
  "HIBCCodablockF",
  options: options,
  ..args,
)
#let hibc-aztec(data, options: (:), ..args) = barcode(
  data,
  "HIBCAztec",
  options: options,
  ..args,
)
#let dotcode(data, options: (:), ..args) = barcode(
  data,
  "DotCode",
  options: options,
  ..args,
)
#let hanxin(data, options: (:), ..args) = barcode(
  data,
  "HanXin",
  options: options,
  ..args,
)
#let mailmark-2d(data, options: (:), ..args) = barcode(
  data,
  "Mailmark2D",
  options: options,
  ..args,
)
#let upus10(data, options: (:), ..args) = barcode(
  data,
  "UPUS10",
  options: options,
  ..args,
)
#let mailmark-4s(data, options: (:), ..args) = barcode(
  data,
  "Mailmark4S",
  options: options,
  ..args,
)
#let azrune(data, options: (:), ..args) = barcode(
  data,
  "AzRune",
  options: options,
  ..args,
)
#let code32(data, options: (:), ..args) = barcode(
  data,
  "Code32",
  options: options,
  ..args,
)
#let gs1-128-cc(data, options: (:), ..args) = barcode(
  data,
  "GS1128CC",
  options: options,
  ..args,
)
#let dbar-omn-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarOmnCC",
  options: options,
  ..args,
)
#let dbar-ltd-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarLtdCC",
  options: options,
  ..args,
)
#let dbar-exp-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarExpCC",
  options: options,
  ..args,
)
#let upca-cc(data, options: (:), ..args) = barcode(
  data,
  "UPCACC",
  options: options,
  ..args,
)
#let upce-cc(data, options: (:), ..args) = barcode(
  data,
  "UPCECC",
  options: options,
  ..args,
)
#let dbar-stk-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarStkCC",
  options: options,
  ..args,
)
#let dbar-omn-stk-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarOmnStkCC",
  options: options,
  ..args,
)
#let dbar-exp-stk-cc(data, options: (:), ..args) = barcode(
  data,
  "DBarExpStkCC",
  options: options,
  ..args,
)
#let channel(data, options: (:), ..args) = barcode(
  data,
  "Channel",
  options: options,
  ..args,
)
#let code-one(data, options: (:), ..args) = barcode(
  data,
  "CodeOne",
  options: options,
  ..args,
)
#let grid-matrix(data, options: (:), ..args) = barcode(
  data,
  "GridMatrix",
  options: options,
  ..args,
)
#let upnqr(data, options: (:), ..args) = barcode(
  data,
  "UPNQR",
  options: options,
  ..args,
)
#let ultra(data, options: (:), ..args) = barcode(
  data,
  "Ultra",
  options: options,
  ..args,
)
#let rmqr(data, options: (:), ..args) = barcode(
  data,
  "RMQR",
  options: options,
  ..args,
)
#let bc412(data, options: (:), ..args) = barcode(
  data,
  "BC412",
  options: options,
  ..args,
)
#let dx-film-edge(data, options: (:), ..args) = barcode(
  data,
  "DXFilmEdge",
  options: options,
  ..args,
)
