accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unlicense",
    "Unicode-DFS-2016",
    "Apache-2.0 WITH LLVM-exception",
    "GPL-3.0",
    "Zlib",
]
