use crate::data::*;
use proc_macro2::TokenStream;
use quote::quote;

/// Generate a `const SYMBOLOGY_SUMMARY: &str = "...";` containing JSON metadata
/// for all symbologies defined in the macro invocation.
pub fn gen_symbology_summary(declaration: &SymbologyDeclaration) -> TokenStream {
    let mut symbologies = Vec::new();

    for variant in &declaration.variants {
        let name = variant.name.to_string();
        let raw = variant
            .raw()
            .map(|r| r.path.segments.last().unwrap().ident.to_string())
            .unwrap_or_default();

        let doc = extract_doc_comments(&variant.attrs);

        let aliases: Vec<String> = variant
            .aliases()
            .map(|a| a.iter().map(|s| s.value()).collect())
            .unwrap_or_default();

        let category = variant.meta("category").map(|s| s.value());
        let kebab_case = variant
            .meta("kebab_case")
            .map(|s| s.value())
            .unwrap_or_else(|| to_kebab(&name));

        let options = match variant.options() {
            Some(SymbologyOptionsDeclaration::Inline { entries, .. }) => {
                entries.iter().map(|e| summarize_option_field(e)).collect()
            }
            Some(SymbologyOptionsDeclaration::Binding { binding, .. }) => {
                vec![OptionFieldSummary {
                    name: String::new(),
                    ty: binding
                        .path
                        .segments
                        .last()
                        .map(|s| s.ident.to_string())
                        .unwrap_or_default(),
                    doc: String::new(),
                    default: None,
                    is_binding: true,
                }]
            }
            None => Vec::new(),
        };

        symbologies.push(SymbologySummary {
            name,
            kebab_case,
            raw,
            doc,
            category,
            aliases,
            options,
        });
    }

    let json = serde_json::to_string_pretty(&symbologies).expect("failed to serialize summary");

    quote! {
        /// JSON metadata for all symbologies, generated by `symbol_data!`.
        pub const SYMBOLOGY_SUMMARY: &str = #json;
    }
}

fn extract_doc_comments(attrs: &[syn::Attribute]) -> String {
    let mut lines = Vec::new();
    for attr in attrs {
        if attr.path().is_ident("doc") {
            if let syn::Meta::NameValue(nv) = &attr.meta {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = &nv.value
                {
                    lines.push(s.value().trim().to_string());
                }
            }
        }
    }
    lines.join("\n")
}

fn summarize_option_field(entry: &SymbologyEntryOption) -> OptionFieldSummary {
    let doc = extract_doc_comments(&entry.attrs);
    let ty = type_to_string(&entry.ty);
    let default = entry.default.as_ref().map(|(_, expr)| {
        let tokens = quote!(#expr);
        tokens.to_string()
    });
    OptionFieldSummary {
        name: entry.name.to_string(),
        ty,
        doc,
        default,
        is_binding: false,
    }
}

fn type_to_string(ty: &syn::Type) -> String {
    let tokens = quote!(#ty);
    tokens.to_string()
}

#[derive(serde::Serialize)]
struct SymbologySummary {
    name: String,
    kebab_case: String,
    raw: String,
    doc: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    category: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    aliases: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    options: Vec<OptionFieldSummary>,
}

/// Best-effort PascalCase to kebab-case conversion.
fn to_kebab(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut result = String::new();
    for i in 0..chars.len() {
        let ch = chars[i];
        if i > 0 {
            let prev = chars[i - 1];
            let next = chars.get(i + 1).copied();
            if ch.is_uppercase() && prev.is_lowercase() {
                result.push('-');
            } else if ch.is_uppercase() && prev.is_uppercase() {
                if let Some(n) = next {
                    if n.is_lowercase() {
                        result.push('-');
                    }
                }
            } else if ch.is_alphabetic() && prev.is_ascii_digit() {
                result.push('-');
            } else if ch.is_ascii_digit() && prev.is_alphabetic() {
                result.push('-');
            }
        }
        result.push(ch.to_ascii_lowercase());
    }
    result
}

#[derive(serde::Serialize)]
struct OptionFieldSummary {
    #[serde(skip_serializing_if = "String::is_empty")]
    name: String,
    ty: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    doc: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    default: Option<String>,
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    is_binding: bool,
}
