use serde::{Deserialize, Serialize};
use zint_wasm_sys::*;
#[derive(Debug, Serialize, Deserialize)]
#[allow(clippy::upper_case_acronyms)]
pub enum Barcode {
    Code11,
    C25Standard,
    C25Matrix,
    C25Inter,
    C25IATA,
    C25Logic,
    C25Ind,
    Code39,
    ExCode39,
    EANX,
    EANXChk,
    GS1128,
    EAN128,
    Codabar,
    Code128,
    DPLEIT,
    DPIDENT,
    Code16k,
    Code49,
    Code93,
    Flat,
    DBarOmn,
    RSS14,
    DBarLtd,
    RSSLtd,
    DBarExp,
    RSSExp,
    Telepen,
    UPCA,
    UPCAChk,
    UPCE,
    UPCEChk,
    Postnet,
    MSIPlessey,
    FIM,
    Logmars,
    Pharma,
    PZN,
    PharmaTwo,
    CEPNet,
    PDF417,
    PDF417Comp,
    PDF417Trunc,
    MaxiCode,
    QRCode,
    Code128AB,
    Code128B,
    AusPost,
    AusReply,
    AusRoute,
    AusRedirect,
    ISBNX,
    RM4SCC,
    DataMatrix,
    EAN14,
    VIN,
    CodablockF,
    NVE18,
    JapanPost,
    KoreaPost,
    DBarStk,
    RSS14Stack,
    DBarOmnStk,
    RSS14StackOmni,
    DBarExpStk,
    RSSExpStack,
    Planet,
    MicroPDF417,
    USPSIMail,
    OneCode,
    Plessey,
    TelepenNum,
    ITF14,
    KIX,
    Aztec,
    DAFT,
    DPD,
    MicroQR,
    HIBC128,
    HIBC39,
    HIBCDM,
    HIBCQR,
    HIBCPDF,
    HIBCMicPDF,
    HIBCCodablockF,
    HIBCAztec,
    DotCode,
    HanXin,
    Mailmark2D,
    UPUS10,
    Mailmark4S,
    Mailmark,
    AzRune,
    Code32,
    EANXCC,
    GS1128CC,
    EAN128CC,
    DBarOmnCC,
    RSS14CC,
    DBarLtdCC,
    RSSLtdCC,
    DBarExpCC,
    RSSExpCC,
    UPCACC,
    UPCECC,
    DBarStkCC,
    RSS14StackCC,
    DBarOmnStkCC,
    RSS14OmniCC,
    DBarExpStkCC,
    RSSExpStackCC,
    Channel,
    CodeOne,
    GridMatrix,
    UPNQR,
    Ultra,
    RMQR,
    BC412,
    Last,
}
impl From<Barcode> for u32 {
    fn from(barcode: Barcode) -> Self {
        match barcode {
            Barcode::Code11 => BARCODE_CODE11,
            Barcode::C25Standard | Barcode::C25Matrix => BARCODE_C25STANDARD,
            Barcode::C25Inter => BARCODE_C25INTER,
            Barcode::C25IATA => BARCODE_C25IATA,
            Barcode::C25Logic => BARCODE_C25LOGIC,
            Barcode::C25Ind => BARCODE_C25IND,
            Barcode::Code39 => BARCODE_CODE39,
            Barcode::ExCode39 => BARCODE_EXCODE39,
            Barcode::EANX => BARCODE_EANX,
            Barcode::EANXChk => BARCODE_EANX_CHK,
            Barcode::GS1128 | Barcode::EAN128 => BARCODE_GS1_128,
            Barcode::Codabar => BARCODE_CODABAR,
            Barcode::Code128 => BARCODE_CODE128,
            Barcode::DPLEIT => BARCODE_DPLEIT,
            Barcode::DPIDENT => BARCODE_DPIDENT,
            Barcode::Code16k => BARCODE_CODE16K,
            Barcode::Code49 => BARCODE_CODE49,
            Barcode::Code93 => BARCODE_CODE93,
            Barcode::Flat => BARCODE_FLAT,
            Barcode::DBarOmn | Barcode::RSS14 => BARCODE_DBAR_OMN,
            Barcode::DBarLtd | Barcode::RSSLtd => BARCODE_DBAR_LTD,
            Barcode::DBarExp | Barcode::RSSExp => BARCODE_DBAR_EXP,
            Barcode::Telepen => BARCODE_TELEPEN,
            Barcode::UPCA | Barcode::UPCAChk => BARCODE_UPCA,
            Barcode::UPCE | Barcode::UPCEChk => BARCODE_UPCE,
            Barcode::Postnet => BARCODE_POSTNET,
            Barcode::MSIPlessey => BARCODE_MSI_PLESSEY,
            Barcode::FIM => BARCODE_FIM,
            Barcode::Logmars => BARCODE_LOGMARS,
            Barcode::Pharma => BARCODE_PHARMA,
            Barcode::PZN => BARCODE_PZN,
            Barcode::PharmaTwo => BARCODE_PHARMA_TWO,
            Barcode::CEPNet => BARCODE_CEPNET,
            Barcode::PDF417 => BARCODE_PDF417,
            Barcode::PDF417Comp | Barcode::PDF417Trunc => BARCODE_PDF417COMP,
            Barcode::MaxiCode => BARCODE_MAXICODE,
            Barcode::QRCode => BARCODE_QRCODE,
            Barcode::Code128AB | Barcode::Code128B => BARCODE_CODE128AB,
            Barcode::AusPost => BARCODE_AUSPOST,
            Barcode::AusReply => BARCODE_AUSREPLY,
            Barcode::AusRoute => BARCODE_AUSROUTE,
            Barcode::AusRedirect => BARCODE_AUSREDIRECT,
            Barcode::ISBNX => BARCODE_ISBNX,
            Barcode::RM4SCC => BARCODE_RM4SCC,
            Barcode::DataMatrix => BARCODE_DATAMATRIX,
            Barcode::EAN14 => BARCODE_EAN14,
            Barcode::VIN => BARCODE_VIN,
            Barcode::CodablockF => BARCODE_CODABLOCKF,
            Barcode::NVE18 => BARCODE_NVE18,
            Barcode::JapanPost => BARCODE_JAPANPOST,
            Barcode::KoreaPost => BARCODE_KOREAPOST,
            Barcode::DBarStk | Barcode::RSS14Stack => BARCODE_DBAR_STK,
            Barcode::DBarOmnStk | Barcode::RSS14StackOmni => BARCODE_DBAR_OMNSTK,
            Barcode::DBarExpStk | Barcode::RSSExpStack => BARCODE_DBAR_EXPSTK,
            Barcode::Planet => BARCODE_PLANET,
            Barcode::MicroPDF417 => BARCODE_MICROPDF417,
            Barcode::USPSIMail | Barcode::OneCode => BARCODE_USPS_IMAIL,
            Barcode::Plessey => BARCODE_PLESSEY,
            Barcode::TelepenNum => BARCODE_TELEPEN_NUM,
            Barcode::ITF14 => BARCODE_ITF14,
            Barcode::KIX => BARCODE_KIX,
            Barcode::Aztec => BARCODE_AZTEC,
            Barcode::DAFT => BARCODE_DAFT,
            Barcode::DPD => BARCODE_DPD,
            Barcode::MicroQR => BARCODE_MICROQR,
            Barcode::HIBC128 => BARCODE_HIBC_128,
            Barcode::HIBC39 => BARCODE_HIBC_39,
            Barcode::HIBCDM => BARCODE_HIBC_DM,
            Barcode::HIBCQR => BARCODE_HIBC_QR,
            Barcode::HIBCPDF => BARCODE_HIBC_PDF,
            Barcode::HIBCMicPDF => BARCODE_HIBC_MICPDF,
            Barcode::HIBCCodablockF => BARCODE_HIBC_BLOCKF,
            Barcode::HIBCAztec => BARCODE_HIBC_AZTEC,
            Barcode::DotCode => BARCODE_DOTCODE,
            Barcode::HanXin => BARCODE_HANXIN,
            Barcode::Mailmark2D => BARCODE_MAILMARK_2D,
            Barcode::UPUS10 => BARCODE_UPU_S10,
            Barcode::Mailmark4S | Barcode::Mailmark => BARCODE_MAILMARK_4S,
            Barcode::AzRune => BARCODE_AZRUNE,
            Barcode::Code32 => BARCODE_CODE32,
            Barcode::EANXCC => BARCODE_EANX_CC,
            Barcode::GS1128CC | Barcode::EAN128CC => BARCODE_GS1_128_CC,
            Barcode::DBarOmnCC | Barcode::RSS14CC => BARCODE_DBAR_OMN_CC,
            Barcode::DBarLtdCC | Barcode::RSSLtdCC => BARCODE_DBAR_LTD_CC,
            Barcode::DBarExpCC | Barcode::RSSExpCC => BARCODE_DBAR_EXP_CC,
            Barcode::UPCACC => BARCODE_UPCA_CC,
            Barcode::UPCECC => BARCODE_UPCE_CC,
            Barcode::DBarStkCC | Barcode::RSS14StackCC => BARCODE_DBAR_STK_CC,
            Barcode::DBarOmnStkCC | Barcode::RSS14OmniCC => BARCODE_DBAR_OMNSTK_CC,
            Barcode::DBarExpStkCC | Barcode::RSSExpStackCC => BARCODE_DBAR_EXPSTK_CC,
            Barcode::Channel => BARCODE_CHANNEL,
            Barcode::CodeOne => BARCODE_CODEONE,
            Barcode::GridMatrix => BARCODE_GRIDMATRIX,
            Barcode::UPNQR => BARCODE_UPNQR,
            Barcode::Ultra => BARCODE_ULTRA,
            Barcode::RMQR => BARCODE_RMQR,
            Barcode::BC412 | Barcode::Last => BARCODE_LAST,
        }
    }
}
