use serde::{Deserialize, Serialize};
use zint_wasm_sys::*;
#[derive(Debug, Serialize, Deserialize)]
#[allow(clippy::upper_case_acronyms)]
#[serde(tag = "type")]
pub enum Symbology {
    Code11,
    C25Standard,
    C25Matrix,
    C25Inter,
    C25IATA,
    C25Logic,
    C25Ind,
    Code39,
    ExCode39,
    EANX,
    EANXChk,
    GS1128,
    EAN128,
    Codabar,
    Code128,
    DPLEIT,
    DPIDENT,
    Code16k,
    Code49,
    Code93,
    Flat,
    DBarOmn,
    RSS14,
    DBarLtd,
    RSSLtd,
    DBarExp,
    RSSExp,
    Telepen,
    UPCA,
    UPCAChk,
    UPCE,
    UPCEChk,
    Postnet,
    MSIPlessey,
    FIM,
    Logmars,
    Pharma,
    PZN,
    PharmaTwo,
    CEPNet,
    PDF417,
    PDF417Comp,
    PDF417Trunc,
    MaxiCode,
    QRCode,
    Code128AB,
    Code128B,
    AusPost,
    AusReply,
    AusRoute,
    AusRedirect,
    ISBNX,
    RM4SCC,
    DataMatrix,
    EAN14,
    VIN,
    CodablockF,
    NVE18,
    JapanPost,
    KoreaPost,
    DBarStk,
    RSS14Stack,
    DBarOmnStk,
    RSS14StackOmni,
    DBarExpStk,
    RSSExpStack,
    Planet,
    MicroPDF417,
    USPSIMail,
    OneCode,
    Plessey,
    TelepenNum,
    ITF14,
    KIX,
    Aztec,
    DAFT,
    DPD,
    MicroQR,
    HIBC128,
    HIBC39,
    HIBCDM,
    HIBCQR,
    HIBCPDF,
    HIBCMicPDF,
    HIBCCodablockF,
    HIBCAztec,
    DotCode,
    HanXin,
    Mailmark2D,
    UPUS10,
    Mailmark4S,
    Mailmark,
    AzRune,
    Code32,
    EANXCC,
    GS1128CC,
    EAN128CC,
    DBarOmnCC,
    RSS14CC,
    DBarLtdCC,
    RSSLtdCC,
    DBarExpCC,
    RSSExpCC,
    UPCACC,
    UPCECC,
    DBarStkCC,
    RSS14StackCC,
    DBarOmnStkCC,
    RSS14OmniCC,
    DBarExpStkCC,
    RSSExpStackCC,
    Channel,
    CodeOne,
    GridMatrix,
    UPNQR,
    Ultra,
    RMQR,
    BC412,
}
impl From<Symbology> for i32 {
    fn from(barcode: Symbology) -> Self {
        match barcode {
            Symbology::Code11 => BARCODE_CODE11,
            Symbology::C25Standard | Symbology::C25Matrix => BARCODE_C25STANDARD,
            Symbology::C25Inter => BARCODE_C25INTER,
            Symbology::C25IATA => BARCODE_C25IATA,
            Symbology::C25Logic => BARCODE_C25LOGIC,
            Symbology::C25Ind => BARCODE_C25IND,
            Symbology::Code39 => BARCODE_CODE39,
            Symbology::ExCode39 => BARCODE_EXCODE39,
            Symbology::EANX => BARCODE_EANX,
            Symbology::EANXChk => BARCODE_EANX_CHK,
            Symbology::GS1128 | Symbology::EAN128 => BARCODE_GS1_128,
            Symbology::Codabar => BARCODE_CODABAR,
            Symbology::Code128 => BARCODE_CODE128,
            Symbology::DPLEIT => BARCODE_DPLEIT,
            Symbology::DPIDENT => BARCODE_DPIDENT,
            Symbology::Code16k => BARCODE_CODE16K,
            Symbology::Code49 => BARCODE_CODE49,
            Symbology::Code93 => BARCODE_CODE93,
            Symbology::Flat => BARCODE_FLAT,
            Symbology::DBarOmn | Symbology::RSS14 => BARCODE_DBAR_OMN,
            Symbology::DBarLtd | Symbology::RSSLtd => BARCODE_DBAR_LTD,
            Symbology::DBarExp | Symbology::RSSExp => BARCODE_DBAR_EXP,
            Symbology::Telepen => BARCODE_TELEPEN,
            Symbology::UPCA | Symbology::UPCAChk => BARCODE_UPCA,
            Symbology::UPCE | Symbology::UPCEChk => BARCODE_UPCE,
            Symbology::Postnet => BARCODE_POSTNET,
            Symbology::MSIPlessey => BARCODE_MSI_PLESSEY,
            Symbology::FIM => BARCODE_FIM,
            Symbology::Logmars => BARCODE_LOGMARS,
            Symbology::Pharma => BARCODE_PHARMA,
            Symbology::PZN => BARCODE_PZN,
            Symbology::PharmaTwo => BARCODE_PHARMA_TWO,
            Symbology::CEPNet => BARCODE_CEPNET,
            Symbology::PDF417 => BARCODE_PDF417,
            Symbology::PDF417Comp | Symbology::PDF417Trunc => BARCODE_PDF417COMP,
            Symbology::MaxiCode => BARCODE_MAXICODE,
            Symbology::QRCode => BARCODE_QRCODE,
            Symbology::Code128AB | Symbology::Code128B => BARCODE_CODE128AB,
            Symbology::AusPost => BARCODE_AUSPOST,
            Symbology::AusReply => BARCODE_AUSREPLY,
            Symbology::AusRoute => BARCODE_AUSROUTE,
            Symbology::AusRedirect => BARCODE_AUSREDIRECT,
            Symbology::ISBNX => BARCODE_ISBNX,
            Symbology::RM4SCC => BARCODE_RM4SCC,
            Symbology::DataMatrix => BARCODE_DATAMATRIX,
            Symbology::EAN14 => BARCODE_EAN14,
            Symbology::VIN => BARCODE_VIN,
            Symbology::CodablockF => BARCODE_CODABLOCKF,
            Symbology::NVE18 => BARCODE_NVE18,
            Symbology::JapanPost => BARCODE_JAPANPOST,
            Symbology::KoreaPost => BARCODE_KOREAPOST,
            Symbology::DBarStk | Symbology::RSS14Stack => BARCODE_DBAR_STK,
            Symbology::DBarOmnStk | Symbology::RSS14StackOmni => BARCODE_DBAR_OMNSTK,
            Symbology::DBarExpStk | Symbology::RSSExpStack => BARCODE_DBAR_EXPSTK,
            Symbology::Planet => BARCODE_PLANET,
            Symbology::MicroPDF417 => BARCODE_MICROPDF417,
            Symbology::USPSIMail | Symbology::OneCode => BARCODE_USPS_IMAIL,
            Symbology::Plessey => BARCODE_PLESSEY,
            Symbology::TelepenNum => BARCODE_TELEPEN_NUM,
            Symbology::ITF14 => BARCODE_ITF14,
            Symbology::KIX => BARCODE_KIX,
            Symbology::Aztec => BARCODE_AZTEC,
            Symbology::DAFT => BARCODE_DAFT,
            Symbology::DPD => BARCODE_DPD,
            Symbology::MicroQR => BARCODE_MICROQR,
            Symbology::HIBC128 => BARCODE_HIBC_128,
            Symbology::HIBC39 => BARCODE_HIBC_39,
            Symbology::HIBCDM => BARCODE_HIBC_DM,
            Symbology::HIBCQR => BARCODE_HIBC_QR,
            Symbology::HIBCPDF => BARCODE_HIBC_PDF,
            Symbology::HIBCMicPDF => BARCODE_HIBC_MICPDF,
            Symbology::HIBCCodablockF => BARCODE_HIBC_BLOCKF,
            Symbology::HIBCAztec => BARCODE_HIBC_AZTEC,
            Symbology::DotCode => BARCODE_DOTCODE,
            Symbology::HanXin => BARCODE_HANXIN,
            Symbology::Mailmark2D => BARCODE_MAILMARK_2D,
            Symbology::UPUS10 => BARCODE_UPU_S10,
            Symbology::Mailmark4S | Symbology::Mailmark => BARCODE_MAILMARK_4S,
            Symbology::AzRune => BARCODE_AZRUNE,
            Symbology::Code32 => BARCODE_CODE32,
            Symbology::EANXCC => BARCODE_EANX_CC,
            Symbology::GS1128CC | Symbology::EAN128CC => BARCODE_GS1_128_CC,
            Symbology::DBarOmnCC | Symbology::RSS14CC => BARCODE_DBAR_OMN_CC,
            Symbology::DBarLtdCC | Symbology::RSSLtdCC => BARCODE_DBAR_LTD_CC,
            Symbology::DBarExpCC | Symbology::RSSExpCC => BARCODE_DBAR_EXP_CC,
            Symbology::UPCACC => BARCODE_UPCA_CC,
            Symbology::UPCECC => BARCODE_UPCE_CC,
            Symbology::DBarStkCC | Symbology::RSS14StackCC => BARCODE_DBAR_STK_CC,
            Symbology::DBarOmnStkCC | Symbology::RSS14OmniCC => BARCODE_DBAR_OMNSTK_CC,
            Symbology::DBarExpStkCC | Symbology::RSSExpStackCC => BARCODE_DBAR_EXPSTK_CC,
            Symbology::Channel => BARCODE_CHANNEL,
            Symbology::CodeOne => BARCODE_CODEONE,
            Symbology::GridMatrix => BARCODE_GRIDMATRIX,
            Symbology::UPNQR => BARCODE_UPNQR,
            Symbology::Ultra => BARCODE_ULTRA,
            Symbology::RMQR => BARCODE_RMQR,
            Symbology::BC412 => BARCODE_LAST,
        }
        .try_into()
        .unwrap()
    }
}
