name: CI
on: [push, pull_request]


jobs:
  test:
    name: Build Typst Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
            targets: wasm32-wasip1
      - run: cargo xtask ci
        env:
            XTASK_TYPST_VERSION: 0.11.1
