use std::fmt::Write;

use crate::{typst_pkg_path, Symbology};

pub fn gen_wrappers(symbologies: &[Symbology]) {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by `cargo run -p generator -- wrappers`").unwrap();
    writeln!(out, "// Do not edit manually.\n").unwrap();
    writeln!(out, "#import \"core.typ\": barcode\n").unwrap();

    for sym in symbologies {
        writeln!(
            out,
            "#let {name}(data, options: (:), ..args) = barcode(\n  \
             data,\n  \
             \"{sym}\",\n  \
             options: options,\n  \
             ..args,\n\
             )",
            name = sym.kebab_case,
            sym = sym.name,
        )
        .unwrap();
    }

    let path = typst_pkg_path().join("wrappers.typ");
    std::fs::write(&path, &out).expect("failed to write wrappers.typ");
    eprintln!("wrote {}", path.display());
}
