use std::fmt::Write;

use crate::{typst_pkg_path, OptionField, Symbology};

pub fn gen_docs(symbologies: &[Symbology]) {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by `cargo run -p generator -- docs`").unwrap();
    writeln!(out, "// Do not edit manually.\n").unwrap();
    writeln!(out, "#import \"@preview/cmarker:0.1.8\": render as md").unwrap();
    writeln!(out, "#import \"manual_util.typ\": *\n").unwrap();

    // Group by category
    let category_order: &[(&str, &str)] = &[
        ("", "General"),
        ("retail", "Retail & Product Identification"),
        ("gs1", "GS1 DataBar"),
        ("2d", "2D Matrix Codes"),
        ("postal", "Postal Services"),
        ("healthcare", "Healthcare & Pharmaceutical"),
    ];

    for &(cat_key, cat_title) in category_order {
        let members: Vec<&Symbology> = symbologies
            .iter()
            .filter(|s| s.category.as_deref().unwrap_or("") == cat_key)
            .collect();
        if members.is_empty() {
            continue;
        }

        writeln!(out, "== {cat_title}\n").unwrap();

        for sym in members {
            write_symbology(&mut out, sym);
        }
    }

    let path = typst_pkg_path().join("manual_gen.typ");
    std::fs::write(&path, &out).expect("failed to write manual_gen.typ");
    eprintln!("wrote {}", path.display());
}

fn write_symbology(out: &mut String, sym: &Symbology) {
    // Heading (level 3)
    writeln!(out, "=== {} <sym-{}>\n", sym.name, sym.kebab_case).unwrap();

    // Aliases
    if !sym.aliases.is_empty() {
        let aliases = sym
            .aliases
            .iter()
            .map(|a| format!("`\"{a}\"`"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "Also accepted as: {aliases}\n").unwrap();
    }

    // Doc (from rustdoc) — render as markdown via cmarker
    if !sym.doc.is_empty() {
        let md = strip_rustdoc_links(&sym.doc).replace('"', "\\\"");
        writeln!(out, "#md(\"{md}\", h1-level: 4)\n").unwrap();
    }

    // Shortcut
    writeln!(
        out,
        "Shortcut: `#{}(data)` \\\nSymbology value: `\"{}\"`\n",
        sym.kebab_case, sym.name
    )
    .unwrap();

    // Options table
    let real_options: Vec<&OptionField> = sym.options.iter().filter(|o| !o.is_binding).collect();

    if !real_options.is_empty() {
        writeln!(out, "*Options:*\n").unwrap();
        writeln!(
            out,
            "#table(\n  \
             columns: (auto, auto, 1fr, auto),\n  \
             align: (left + horizon, center + horizon, left + horizon, center + horizon),\n  \
             stroke: gray.lighten(60%),\n  \
             fill: (_, row) => if row == 0 {{ blue.lighten(80%) }},\n  \
             [*Option*], [*Type*], [*Description*], [*Default*],"
        )
        .unwrap();

        for opt in &real_options {
            let name = &opt.name;
            let ty = rust_type_to_typst_badge(&opt.ty);
            let doc = if opt.doc.is_empty() {
                "--".to_string()
            } else {
                let md = strip_rustdoc_links(&opt.doc).replace('"', "\\\"");
                format!("#md(\"{md}\", h1-level: 5)")
            };
            let default = opt
                .default
                .as_deref()
                .map(|d| format!("`{d}`"))
                .unwrap_or_else(|| "--".to_string());

            writeln!(out, "  [`{name}`], {ty}, [{doc}], [{default}],").unwrap();
        }

        writeln!(out, ")\n").unwrap();
    } else if sym.options.iter().any(|o| o.is_binding) {
        let binding = sym.options.iter().find(|o| o.is_binding).unwrap();
        writeln!(out, "_Uses shared options from `{}`._\n", binding.ty).unwrap();
    }
}

/// Strip rustdoc-style links: [`Foo`][Bar::Baz] → `Foo`, [`Foo`] → `Foo`
fn strip_rustdoc_links(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '[' && chars.peek() == Some(&'`') {
            chars.next(); // skip opening `
            let mut display = String::new();
            loop {
                match chars.next() {
                    Some('`') => {
                        if chars.peek() == Some(&']') {
                            chars.next();
                        }
                        break;
                    }
                    Some(c) => display.push(c),
                    None => break,
                }
            }
            // Skip optional [link target]
            if chars.peek() == Some(&'[') {
                chars.next();
                loop {
                    match chars.next() {
                        Some(']') | None => break,
                        _ => {}
                    }
                }
            }
            result.push('`');
            result.push_str(&display);
            result.push('`');
        } else {
            result.push(ch);
        }
    }

    result
}

/// Map Rust type strings to typst type badge calls.
fn rust_type_to_typst_badge(ty: &str) -> String {
    let ty = ty.trim();

    // Option<T> → show the inner type
    if let Some(inner) = ty
        .strip_prefix("Option")
        .and_then(|s| s.trim().strip_prefix('<'))
        .and_then(|s| s.trim().strip_suffix('>'))
    {
        return rust_type_to_typst_badge(inner);
    }

    match ty {
        "bool" => "typst-type(\"bool\")".to_string(),
        "usize" | "u8" | "u16" | "u32" | "i32" | "i64" => "typst-type(\"int\")".to_string(),
        "f32" | "f64" => "typst-type(\"float\")".to_string(),
        "String" | "&str" => "typst-type(\"str\")".to_string(),
        _ => {
            let short = ty.split("::").last().unwrap_or(ty).trim();
            format!("[`{short}`]")
        }
    }
}
